### ISSUE TITLE
flipstore .fap

### ISSUE THREAD

**Issue by Gellaci75** [jblanked/FlipStore#1]
Ich möchte ein flipstore.fap 
Wie geht es?

**Comment by jblanked** [comment]
Hello. You can either use `ufbt` to compile it, or download it from https://www.flipsocial.net/download/flip_store

**Comment by Gellaci75** [comment]
Dankeschön!
Geht es über usb kabel?

JBlanked ***@***.***> ezt írta (időpont: 2024. dec. 8., V,
23:14):
